### ISSUE TITLE
Rollout new release on npmjs.org

### ISSUE THREAD

**Issue by vergissberlin** [Marak/play.js#10]
Hi!

Please renew the package on npmjs.org! The example described in the documentation leads to the following error message:

``` bash
, require, module, __filename, __dirname) { var play = require('play').Play();
                                                                       ^
TypeError: Object #<Object> has no method 'Play'
    at Object.<anonymous> (/home/pi/test/sound/demo.js:1:90)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Thank you!
kindly regards, André

**Comment by cauli** [comment]
+1. I've wasted some time to realise the npm version was outdated :package:

**Comment by vergissberlin** [comment]
**So pleaaaase!**

```
npm config set sign-git-tag true
npm version patch
npm publish
```

:+1:

**Comment by vergissberlin** [comment]
Hey, i must push this issue because I need it urgently.
_Hopefully you act soon._

**Comment by cauli** [comment]
@vergissberlin I think you'll be better off by forking the repo and publishing it yourself : D

**Comment by omarojo** [comment]
@cauli So how can we use this latest version without using the 'npm install' method ?

**Comment by cauli** [comment]
@omarojo Easy, just clone this project (or anu interesting forks of it) from github to your machine. You'll have to check for changes in this project manually, but since it doesn't update since 2011 you may as well forget about it... If you need to make changes to play.js, fork the project then clone it.
