### ISSUE TITLE
Unhandled 'error' event

### ISSUE THREAD

**Issue by ghost** [Marak/play.js#12]
can you tell me what im doing wrong?

> var player =  require('play');

> player.sound('./noti.wav')

it says:

> playing=>./noti.wav
> events.js:160
>       throw er; // Unhandled 'error' event
>       ^

> Error: spawn afplay ENOENT
>     at exports._errnoException (util.js:1020:11)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:32)
>     at onErrorNT (internal/child_process.js:376:16)
>    at _combinedTickCallback (internal/process/next_tick.js:80:11)
>    at process._tickCallback (internal/process/next_tick.js:104:9)

or is it a bug?

**Comment by krzysztofKKW** [comment]
Same issue.

**Comment by chenbont** [comment]
我也是遇到这个错误
