### ISSUE TITLE
Me ajuda

### ISSUE THREAD

**Issue by ryanrsps** [Marak/play.js#17]
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'colors'
Require stack:
- C:\Users\ryanr\OneDrive\Área de Trabalho\Lofy-SelfBot-V4\index.js
←[90m    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:746:27)←[39m
←[90m    at Module.require (internal/modules/cjs/loader.js:974:19)←[39m
←[90m    at require (internal/modules/cjs/helpers.js:93:18)←[39m
    at Object.<anonymous> (C:\Users\ryanr\OneDrive\Área de Trabalho\Lofy-SelfBot-V4\index.js:1:1236)
←[90m    at Module._compile (internal/modules/cjs/loader.js:1085:14)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:950:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:790:12)←[39m
←[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\ryanr\\OneDrive\\Área de Trabalho\\Lofy-SelfBot-V4\\index.js'←[39m
  ]
}

**Comment by CactusHamster** [comment]
You need to install the dependency. Using `npm i` should work, or using `npm i colors --save`.
