### ISSUE TITLE
Uncaught Error Error: spawn afplay ENOENT

### ISSUE THREAD

**Issue by Justice603-tech** [Marak/play.js#18]
Every single time i try to play my .mp3 song file i downloaded. i get this error
```
Uncaught Error Error: spawn afplay ENOENT
    at __node_internal_captureLargerStackTrace (internal/errors:490:5)
    at __node_internal_errnoException (internal/errors:620:12)
    at ChildProcess._handle.onexit (internal/child_process:285:19)
    at onErrorNT (internal/child_process:483:16)
    at processTicksAndRejections (internal/process/task_queues:82:21)
    --- TickObject ---
    at init (internal/inspector_async_hook:25:19)
    at emitInitNative (internal/async_hooks:202:43)
    at emitInitScript (internal/async_hooks:506:3)
    at nextTick (internal/process/task_queues:132:5)
    at ChildProcess.spawn (internal/child_process:403:13)
    at spawn (child_process:757:9)
    at exports.sound (c:\Users\saico\OneDrive\Documents\SongManager\node_modules\play\lib\play.js:57:17)
    at PlaySong (c:\Users\saico\OneDrive\Documents\SongManager\songmanager.js:8:12)
    at <anonymous> (c:\Users\saico\OneDrive\Documents\SongManager\songmanager.js:18:6)
    at Module._compile (internal/modules/cjs/loader:1275:14)
    at Module._extensions..js (internal/modules/cjs/loader:1329:10)
    at Module.load (internal/modules/cjs/loader:1133:32)
    at Module._load (internal/modules/cjs/loader:972:12)
    at executeUserEntryPoint (internal/modules/run_main:83:12)
    at <anonymous> (internal/main/run_main_module:23:47)
```

# Screenshot
![Screenshot](https://user-images.githubusercontent.com/105648910/229273046-8f19d267-361d-4481-bc6a-e8b2f5501034.png)

**Comment by cezarsmpio** [comment]
Same issue here, did you get it fixed?
