### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by eguvenc** [Marak/play.js#6]
When i run below the code i get an error.

<code>
var play = require('play');
  // play with a callback
play.sound('./wavs/sfx/intro.wav', function(){ });
</code>

<code>
   info  - socket.io started
playing=>./wavs/sfx/intro.wav

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:975:11)
    at Process.ChildProcess._handle.onexit (child_process.js:766:34)
</code>

**Comment by paultanner** [comment]
I'm getting the same error.  Hard to fix as it's deep in parts of node itself.
I have node v0.10.7 built on Wheezy/Debian

Con-incidentally, its also at events.js:72.  Some kind of unhandled error.

Also, on the readme you say  var play = require('play').Play();
I think this should be  var play = require('play');
And you call play.on which does not seem to exist in class.

Paul

**Comment by watsoncj** [comment]
Some platforms (such as Debian) don't trigger the `exit` event after a failed spawn. It will trigger the `error` event instead. Since play.js isn't handling the error event the process is terminated.

**Comment by MichaelMcKavanagh** [comment]
I get pretty much get every error listed above, from my perspective this module is completely broken. :/
